#!/bin/sh

talk=openfoam

rsync -HavP ./  /home/pres/$talk/
rm -rf /home/pres/$talk/ui
rsync -HavP ../ui/  /home/pres/$talk/ui/
find /home/pres/$talk -exec chmod gou+r {} \;
find /home/pres/$talk -type d -exec chmod gou+rx {} \;
